sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

jobs:
  include:
    - stage: test
      node_js: '8'
      if: tag IS blank
      script:
        - npm run lint
        - npm run ava
    - stage: semantic release
      node_js: '8'
      if: branch IS master
      script:
        - npm run travis-deploy-once "npm run semantic-release"
    - stage: docker release
      node_js: '8'
      if: tag IS present
      script:
        - docker run build -t allovince/avnpc .
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/avnpc:latest;
        - docker push allovince/avnpc:$TRAVIS_TAG;
