sudo: false
language: node_js
notifications:
  email: false
install: true

jobs:
  include:
    - stage: test
      node_js: '10'
      if: branch = master AND tag IS blank
      script:
        - npm install
        - npm run lint
        - npm run ava
        - npm run travis-deploy-once "npm run semantic-release"
    - stage: docker release
      node_js: '10'
      if: tag IS present
      script:
        - make travis-build-log
        - docker build -t allovince/avnpc .
        - docker tag allovince/avnpc allovince/avnpc:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/avnpc:latest;
        - docker push allovince/avnpc:$TRAVIS_TAG;
