language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run ava
      if: tag IS blank
    - stage: semantic release
      node_js: '9'
      script:
        - npm run travis-deploy-once "npm run semantic-release"
      if: (tag IS blank) AND (branch IS master)
    - stage: docker release
      node_js: '8'
      script:
        - docker run build allovince/avnpc
        - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/avnpc:latest;
        - docker push allovince/avnpc:$TRAVIS_TAG;
      if: tag IS present
